spring:
  application:
    name: bureauCep
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/testDb
    username: cpc
    password: q1w2e3r4
    driver-class-name: org.h2.Driver
    
server:
  servlet:
    context-path: /bureauCep
    
#http://localhost:8080/bureauCep/swagger-ui.html
    